[pytest]
testpaths = tests
markers =
    Integration: marks tests as integration tests (deselect with '-m "not integration"')
    Unit: marks tests as unit tests (deselect with '-m "not unit"') 
    System: marks tests as system tests (deselect with '-m "not system"')
    AprilRelease: marks tests as part of the April release (deselect with '-m "not aprilrelease"')
    SanityTest: marks tests as sanity tests (deselect with '-m "not sanitytest"')
    RegressionTest: marks tests as regression tests (deselect with '-m "not regressiontest"')

    